baseURL = 'https://smbat.sandm.cc/'
languageCode = 'en-us'
title = 'Smbat Voskanyan'
theme = ['hugo-embed-pdf-shortcode', 'stack']

[languages.en]
    languageName = 'English'
    title = 'Smbat Voskanyan'
    weight = 1
[languages.en.params]
    description = "Smbat Voskanyan's Portfolio Page"

enableInlineShortcodes = true

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguag = 'en'

[params]
    mainSections = [ 'post' ]
    featuredImageField = 'image'
    rssFullContent = true
    favicon = '/favicon.ico'
[params.sidebar]
    emoji = 'ğŸ¥'
    subtitle = "Seasoned C++ programmer with a passion for graphics and game engine development. Six+ years of experience across various programming domains, including AI, compilers, and gameplay. Currently honing my skills with a Master's in Game Design at Uppsala University. Avatar by @ğš–ğšŠğš›ğš’ğšŠ_ğšœğš˜ğšğš—ğšğš›_ğšŠğš›ğš"
    enabled = true
    compact = false
[params.sidebar.avatar]
    local = true
    src = "img/avatar.png"
[params.article]
    math = false
    toc = true
    readingTime = true
[params.article.license]
    enabled = true
    default = 'Licensed under CC BY-NC-SA 4.0'

# [[params.widgets.homepage]]
# type = "search"
# 
# [[params.widgets.homepage]]
# type = "archives"
# 
#   [params.widgets.homepage.params]
#   limit = 5
# 
[[params.widgets.homepage]]
type = "categories"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

  [params.widgets.homepage.params]
  limit = 10
# 
# [[params.widgets.page]]
# type = "toc"

[params.colorScheme]
toggle = true
default = "light"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[menu]
main = [ ]

    [[menu.social]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/TheSenPie"

    [menu.social.params]
        icon = "brand-github"

    [[menu.social]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://twitter.com/TheSenPie"

    [menu.social.params]
        icon = "brand-twitter"

    [[menu.social]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/smbat-voskanyan-64676915b/"

    [menu.social.params]
        icon = "brand-linkedin"

[related]
includeNewer = true
threshold = 60
toLower = false

    [[related.indices]]
    name = "tags"
    weight = 100

    [[related.indices]]
    name = "categories"
    weight = 200

[markup.goldmark.renderer]
unsafe = true # Set to true if you have HTML content inside Markdown

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4